Update patch set 1
Patch Set 1: Fails

Breaks the build with (I will handle this):


development/tools/emulator/opengl/tests/gles_android_wrapper/egl.cpp: In function 'EGLBoolean eglQuerySurface(void*, void*, EGLint, EGLint*)':
development/tools/emulator/opengl/tests/gles_android_wrapper/egl.cpp:411: error: invalid operands of types 'EGLint*' and 'int' to binary 'operator|'
development/tools/emulator/opengl/tests/gles_android_wrapper/egl.cpp:411: error:   in evaluation of 'operator|=(EGLint*, int)'
make: *** [out/target/product/generic/obj/SHARED_LIBRARIES/libEGL_emul_intermediates/egl.o] Error 1


Also, the use of getpid() is a bit suspicious for windows, will check it.

Patch-set: 1