Update patch set 5
Patch Set 5: Fails; Do not submit

This unfortunately breaks the build:

In file included from development/tools/emulator/opengl/system/GLESv1/gl.cpp:9:
out/target/product/generic/obj/SHARED_LIBRARIES/libGLESv1_enc_intermediates/gl_ftable.h:255: error: 'glMultiDrawArraysSUN' was not declared in this scope
out/target/product/generic/obj/SHARED_LIBRARIES/libGLESv1_enc_intermediates/gl_ftable.h:256: error: 'glMultiDrawElementsSUN' was not declared in this scope
out/target/product/generic/obj/SHARED_LIBRARIES/libGLESv1_enc_intermediates/gl_ftable.h:284: error: too many initializers for '_gl_funcs_by_name'
out/target/product/generic/obj/SHARED_LIBRARIES/libGLESv1_enc_intermediates/gl_ftable.h:284: error: too many initializers for '_gl_funcs_by_name'

Patch-set: 5
Label: Code-Review=-2
Label: Verified=-1