Update patch set 3
Patch Set 3:

> > ImportError: No module named mock
 > >
 > > did we document how to install that somewhere? (should we add it
 > to
 > > external?)
 > 
 > Good question, I think that's beyond my pay grade. :)
 > 
 > Looks like I did `pip install -U mock' on my machines a few months
 > ago. https://android-review.googlesource.com/#/c/161448/5//COMMIT_MSG@22

sudo that -- after sudo apt-get install python-pip -- fixed it for me. (i switched machine since the last time i ran these.)

i get a lot of ERRORs with this patch that i don't get without it.

  test_install_argument_escaping (test_device.ArgumentEscapingTest)
  Make sure that install argument escaping works. ... FAIL
  test_shell_escaping (test_device.ArgumentEscapingTest)
  Make sure that argument escaping is somewhat sane. ... ok
  test_pull (test_device.FileOperationsTest)
  Pull a randomly generated file from specified device. ... ok
  test_pull_dir (test_device.FileOperationsTest)
  Pull a randomly generated directory of files from the device. ... ok
  test_push (test_device.FileOperationsTest)
  Push a randomly generated file to specified device. ... ok
  test_sync (test_device.FileOperationsTest)
  Sync a randomly generated directory of files to specified device. ... ok
  test_unicode_paths (test_device.FileOperationsTest)
  Ensure that we can support non-ASCII paths, even on Windows. ... ok
  test_forward_reverse (test_device.ForwardReverseTest)
  Send data through adb forward and read it back via adb reverse ... ERROR
  test_arg_beats_env (test_device.GetDeviceTest) ... ok
  test_explicit (test_device.GetDeviceTest) ... ok
  test_from_env (test_device.GetDeviceTest) ... ok
  test_no_such_device (test_device.GetDeviceTest) ... ok
  test_no_unique_device (test_device.GetDeviceTest) ... ok
  test_unique_device (test_device.GetDeviceTest) ... ok
  test_root_unroot (test_device.RootUnrootTest)
  Make sure that adb root and adb unroot work, using id(1). ... ERROR
  test_can_distinguish_tricky_results (test_device.ShellTest) ... ERROR
  test_cat (test_device.ShellTest)
  Check that we can at least cat a file. ... ERROR
  test_default_pty_logic (test_device.ShellTest)
  Verify default PTY logic for shells. ... ERROR
  test_line_endings (test_device.ShellTest)
  Ensure that line ending translation is not happening in the pty. ... ERROR
  test_non_interactive_sigint (test_device.ShellTest)
  Tests that SIGINT in a non-interactive shell kills the process. ... ERROR
  test_non_interactive_stdin (test_device.ShellTest)
  Tests that non-interactive shells send stdin. ... ERROR
  test_output_not_stripped (test_device.ShellTest) ... ERROR
  test_pty_arguments (test_device.ShellTest)
  Tests the -T and -t arguments to manually control PTY. ... ERROR
  test_shell_nocheck_failure (test_device.ShellTest) ... ERROR
  test_shell_nocheck_output_not_stripped (test_device.ShellTest) ... ERROR
  test_shell_protocol (test_device.ShellTest)
  Tests the shell protocol on the device. ... ERROR
  test_throws_on_failure (test_device.ShellTest) ... ERROR
  test_get_prop (test_device.SystemPropertiesTest) ... ERROR
  test_set_prop (test_device.SystemPropertiesTest) ... ERROR
  test_tcpip_failure_raises (test_device.TcpIpTest)
  adb tcpip requires a port. ... ERROR

all seem to be

  DeviceNotFoundError: No device with serial HT4AZSM00204

i'm afk for the next couple of days but i'll look closer when i'm back.

Patch-set: 3
Label: Verified=0