Update patch set 1
Patch Set 1: Do not submit

It seems this breaks the Linux build (see below). Also, I think there are too much stuff in this patch. I would really appreciate if you could split this into several dependent patches. E.g. one with the corresponding non-Windows-specific library changes, one for the Windows-specific changes, and another one for the final tests programs.

Thanks


/usr/bin/ld: warning: libGLcommon.so, needed by out/host/linux-x86/obj/lib/libEGL_translator.so, not found (try using -rpath or -rpath-link)
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::setObjectData(NamedObjectType, unsigned int, SmartPtr<ObjectData, false>)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::replaceGlobalName(NamedObjectType, unsigned int, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::genName(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::ObjectNameManager()'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::createShareGroup(void*)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::deleteName(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::~ObjectNameManager()'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::getGlobalContext()'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ShareGroup::getGlobalName(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::isObject(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ShareGroup::~ShareGroup()'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ShareGroup::getObjectData(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::attachShareGroup(void*, void*)'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `isPowerOf2(int)'

Patch-set: 1
Reviewer: David Turner <1000411@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=-2
Label: Verified=0