Update patch set 5
Patch Set 5: Fails; I would prefer that you didn't submit this

Right now, this breaks the Linux build if the correct headers are not installed (or more specifically if libgl1-mesa-dev is not installed). I would prefer if you could add a guard environment variable to disable building this module by default.

We will need to update all build servers before making this the default, or stuff will break hideously.

Thanks for your comprehension.

error: GL/glx.h: No such file or directory

Patch-set: 5
Label: Code-Review=-1