Update patch set 1
Patch Set 1:

Does this really not need any API changes this time? I tried building it just now, and it broke.

Among other things:
```
bionic/tools/versioner/src/Preprocessor.cpp:449:17: error: no viable conversion from 'llvm::StringRef' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')                                                
    std::string rel_path = path.substr(src_dir.length() + 1);                                                   
                ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                           
```

Patch-set: 1
CC: Gerrit User 1010056 <1010056@85c56323-6fa9-3386-8a01-6480fb634889>