Update patch set 2
Patch Set 2: Fails

This breaks the full-eng build. Apparently a missing dependency:


host C++: libGLESv2_dec <= out/host/linux-x86/obj/SHARED_LIBRARIES/libGLESv2_dec_intermediates/gl2_dec.cpp
/usr/bin/ld: warning: libGLcommon.so, needed by out/host/linux-x86/obj/lib/libEGL_translator.so, not found (try using -rpath or -rpath-link)
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetIntegerv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glIsEnabled'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::~GLEScontext()'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glCullFace'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glLoadIdentity'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetError'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::setObjectData(NamedObjectType, unsigned int, SmartPtr<ObjectData, false>)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::enableArr(unsigned int, bool)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::replaceGlobalName(NamedObjectType, unsigned int, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glDepthRange'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::genName(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexParameteriv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetTexEnviv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glColorMask'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glMultMatrixf'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glAlphaFunc'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::bindBuffer(unsigned int, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glOrtho'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glPointParameterfv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexSubImage2D'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexCoordPointer'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glFinish'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::getBufferSize(unsigned int, int*)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLESvalidate::textureEnum(unsigned int, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::setGLerror(unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::isBindedBuffer(unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glStencilMask'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexParameterfv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glRotatef'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glFrustum'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glPopMatrix'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glMaterialf'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glBindTexture'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glClear'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glDisable'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::ObjectNameManager()'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glMaterialfv'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::createShareGroup(void*)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexEnvi'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glCopyTexSubImage2D'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glLightModelfv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glFrontFace'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetLightfv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetTexParameteriv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glFlush'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `typeinfo for GLEScontext'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `ShareGroup::deleteName(NamedObjectType, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glMultiTexCoord4f'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLESpointer::GLESpointer()'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glReadPixels'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLESvalidate::pixelFrmt(unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glLightf'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::isArrEnabled(unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glPolygonOffset'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glMatrixMode'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glColorPointer'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::chooseConvertMethod(GLESFloatArrays&, int, int, unsigned int, void const*, bool, GLESpointer*, unsigned int, unsigned int&)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetTexEnvfv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::dispatchFuncs(GLESVersion)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glCopyTexImage2D'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexParameterf'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glHint'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glIsTexture'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glGetFloatv'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glFogf'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glShadeModel'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::GLEScontext()'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLEScontext::setBufferData(unsigned int, long, void const*, unsigned int)'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLESpointer::getBufferData() const'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glDepthMask'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glNormal3f'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glLightModelf'
out/host/linux-x86/obj/lib/libEGL_translator.so: undefined reference to `ObjectNameManager::~ObjectNameManager()'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glPointParameterf'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glTexImage2D'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glDisableClientState'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glClipPlane'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLDispatch::glClearDepth'
out/host/linux-x86/obj/lib/libGLES_CM_translator.so: undefined reference to `GLESvalidate::pixelOp(unsigned int, unsigned int)'

Patch-set: 2
Label: Verified=-1