Update patch set 1
Patch Set 1: Autosubmit+1 Presubmit-Ready+1

presubmit fails due to fetch error.

FatalSyncError: Failed to fetch project platform/packages/services/Car

Patch-set: 1
Reviewer: Gerrit User 1322948 <1322948@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Autosubmit=+1
Label: Presubmit-Ready=+1